import Head from 'next/head'
import First from '../components/First'

const Home = () => {
  return (
    <div>
      <Head>
        <title>test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <First />
      </main>
    </div>
  )
}

export default Home
